# helm upgrade --install svc-mux ./chart --namespace svc-mux --values test-local/values.yaml
args:
  - run
  - --verbose
  - --standalone
  - --all-namespaces
  - --liveness=http://0.0.0.0:8081/healthz
  - /app/main.py
