{{- if .Values.defaultLoadBalancer.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.defaultLoadBalancer.name }}
  labels:
    {{- include "lb4-multiplexer.labels" . | nindent 4 }}
    {{- with .Values.defaultLoadBalancer.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  annotations:
    helm.sh/resource-policy: keep
    {{ printf "%s/multiplexer" .Values.api.prefix | quote }}: "true"
    {{- with .Values.defaultLoadBalancer.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  type: LoadBalancer
  {{- with .Values.defaultLoadBalancer.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}
  allocateLoadBalancerNodePorts: {{ .Values.defaultLoadBalancer.allocateLoadBalancerNodePorts }}
  {{- with .Values.defaultLoadBalancer.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.defaultLoadBalancer.internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.defaultLoadBalancer.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  ports:
    - name: placeholder
      protocol: TCP
      port: 101
{{- end }}
