apiVersion: v1
kind: Pod
metadata:
  name: "probe"
  namespace: default
  labels:
    app: "probe"
spec:
  terminationGracePeriodSeconds: 1
  containers:
    - name: probe
      image: "alpine/k8s:1.28.4"
      imagePullPolicy: IfNotPresent
      command: ["sleep", "infinity"]
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
  restartPolicy: Always
